service: go-away-kitty

# Please ensure the serverless-openwhisk provider plugin is installed globally.
# $ npm install -g serverless-openwhisk
# ...before installing project dependencies to register this provider.
# $ npm install
provider:
  name: openwhisk

functions:
  processImage:
    handler: handlers/imageLabels.imageLabels
    events:
      # - http:
      #     path: /analyze/image
      #     method: post

# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-openwhisk
